# Generated by Django 3.2.3 on 2021-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prerregistro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('genero', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=16)),
                ('lugar', models.CharField(max_length=100)),
                ('recibir_correos', models.BooleanField()),
                ('emprendedor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'prerregistro',
            },
        ),
    ]
